# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LinearRegression
                                 A QGIS plugin
 Linear regression in spatial data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-22
        copyright            : (C) 2024 by Lee/LSDS
        email                : mpk6604@uos.ac.kr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

from PyQt5.QtWidgets import QAction
from qgis.PyQt.QtCore import QCoreApplication
from .LinearRegressionDialog import LinearRegressionDialog

class LinearRegression:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface
        self.dlg = None

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""
        self.action = QAction("Linear Regression", self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToMenu("&Linear Regression", self.action)

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        self.iface.removeToolBarIcon(self.action)
        self.iface.removePluginMenu("&Linear Regression", self.action)

    def run(self):
        """Run method that performs all the real work"""
        if self.dlg is None:
            self.dlg = LinearRegressionDialog()
        self.dlg.show()
        self.dlg.exec_()
        
def classFactory(iface):
    """Load LinearRegression class from file LinearRegression."""
    return LinearRegression(iface)